name: React CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: cd client && npm ci
    - name: Build
      run: cd client && npm run build --if-present
      env:
        VITE_REACT_APP_API_URL1: ${{ secrets.VITE_REACT_APP_API_URL1 }}
        VITE_REACT_APP_API_URL2: ${{ secrets.VITE_REACT_APP_API_URL2 }}
        